# Generated by Django 3.2 on 2021-04-14 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="menu.category",
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="categories",
            field=models.ManyToManyField(to="menu.Category"),
        ),
    ]
