# Generated by Django 3.2 on 2021-04-14 17:15

import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_auto_20210414_1714"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="illustration",
            field=models.ImageField(
                blank=True, null=True, upload_to=menu.models.category_upload_to
            ),
        ),
    ]
