# Generated by Django 3.2 on 2021-04-28 16:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_illustration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='screen',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='ordering'),
        ),
        migrations.AddField(
            model_name='product',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='ordering'),
        ),
        migrations.AddField(
            model_name='screen',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='ordering'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='menu.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='priceEuroCents',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)], verbose_name='Price in euro cents'),
        ),
    ]
